apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: compositiondefinition-{{ .Release.Name }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.chart }}
  chart:
    {{- toYaml . | nindent 4 }}
  {{- end }}
